Хм, а что значит huix?
plasmoapp/plasmo-voice pull request #100
Opened 2021-10-17 14:24 UTC by Chexit

Наверное значит самый лучший дизайнер в мире

2021-10-17 14:29 UTC, thehaffk requested changes
говно

2021-10-17 14:32 UTC, Chexit commented
> говно

говно

2021-10-17 14:34 UTC, Chexit commented
> говно
Ты 24/7 смотришь реквесты?

2021-10-17 23:10 UTC, apehum requested changes
Ну и жди еще одно ревью от кпидса pepeLaugh

2021-10-17 23:10 UTC, Apehum commented on common/src/main/resources/assets/plasmo_voice/lang/ru_ru.json
> +    "gui.plasmo_voice.about.huix": "Концепт и Дизайн", // KEKW
В json'e нельзя использовать комментарии, убери

2021-10-17 23:10 UTC, Apehum commented on common/src/main/resources/assets/plasmo_voice/lang/ru_ru.json
> +    "gui.plasmo_voice.general.activation.threshold.tooltip_8": "тестирование микрофона и услышать ваш голос.",
Убери тогда уж лишнее "тестирование"

2021-10-18 05:48 UTC, Toldoven commented
Я пофикшу опечатку с "тестрированием", в остальном хуйня

2021-10-18 05:48 UTC, closed without merging